// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX4tFO6y67HEUIrRela2t6N4XGqRFBaGQ',
    appId: '1:1093654951911:web:3a046eb2a2ed249052ef42',
    messagingSenderId: '1093654951911',
    projectId: 'hotelio-apps-855c2',
    authDomain: 'hotelio-apps-855c2.firebaseapp.com',
    storageBucket: 'hotelio-apps-855c2.appspot.com',
    measurementId: 'G-MF1R0E05Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkP4GxZbrcgRkghnBgNCktpuoM5A05Wt4',
    appId: '1:1093654951911:android:f20159672964897f52ef42',
    messagingSenderId: '1093654951911',
    projectId: 'hotelio-apps-855c2',
    storageBucket: 'hotelio-apps-855c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5MiQITC3QebkNkZ4SXF3varxwaQYtHWI',
    appId: '1:1093654951911:ios:cef6dba00459cb2c52ef42',
    messagingSenderId: '1093654951911',
    projectId: 'hotelio-apps-855c2',
    storageBucket: 'hotelio-apps-855c2.appspot.com',
    iosClientId: '1093654951911-k84ugiv6bkpvf5q5q09hek3hl7dlek2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHotelBookingApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5MiQITC3QebkNkZ4SXF3varxwaQYtHWI',
    appId: '1:1093654951911:ios:cef6dba00459cb2c52ef42',
    messagingSenderId: '1093654951911',
    projectId: 'hotelio-apps-855c2',
    storageBucket: 'hotelio-apps-855c2.appspot.com',
    iosClientId: '1093654951911-k84ugiv6bkpvf5q5q09hek3hl7dlek2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHotelBookingApps',
  );
}
